---

- name: Procedemos a crear el punto de montaje donde queremos montar el recurso.
  file:
    path: /mnt/nfs
    state: directory
    
- name: Creamos la entrada en /etc/fstab y montamos
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: 192.168.1.115:/srv/nfs
    path: /mnt/nfs
    
- name: Activar m칩dulo del kernel br_netfilter (modprobe br_netfilter) 
  modprobe:
    name: br_netfilter
    state: present
    
- name: Activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN (firewall-cmd --add-masquerade --permanent)
  firewalld:
    masquerade: 'yes'
    state: enabled
    permanent: yes
    immediate: yes
    
- name: Copiar k8s.conf para permitir que kubernetes maneje correctamente el tr치fico con el cortafuegos
  copy: src=k8s.conf dest=/etc/sysctl.d/k8s.conf
  
- name: Aplicar cambios en archivo k8s.conf (sysctl --system)
  shell: sysctl --system
  
- name: A침adiendo repositorio de Docker (dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo)
  get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo
    
- name: Instalamos docker que ser치 el engine para ejecutar contenedores (dnf install docker-ce-20.10.6-3.el8 -y)
  dnf:
    name: docker-ce-20.10.6-3.el8 
    state: present
    
- name: Service Docker habilitado y arrancado al incio (systemctl enable docker && systemctl start docker)
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started

- name: Copiar kubernetes.repo para configurar el repositorio de kubernetes
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
  
- name: Instalamos kubernetes (dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes)
  dnf: 
    name:
      - kubelet
      - kubeadm
      - kubectl 
    state: present
    update_cache: yes
    disable_excludes: kubernetes
    
- name: Kubernetes habilitado y arrancado al inicio. (systemctl enable kubelet && systemctl start kubelet)
  systemd:
    name: kubelet    
    state: started
    enabled: yes
    daemon_reload: yes
    
    