---

- hosts: workers
  become: yes
  vars_files:
  - token_variable
  tasks:
  - name: Copiamos el comando para unirnos al cluster a los nodos workers
    copy: src={{ token_file }} dest=join_token.sh

  - name: Unimos los workers al Cluster Kubernetes
    shell: |
     sh join_token.sh
